apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: immich-postgres-direct
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-postgres-direct-pv
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: immich-postgres-direct
  local:
    path: /srv/immich-postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - homeserver

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres-direct-pvc
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: immich-postgres-direct
  volumeName: immich-postgres-direct-pv
  resources:
    requests:
      storage: 20Gi