apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://immich-app.github.io/immich-charts'
    chart: immich
    targetRevision: "0.8.4"
    helm:
      values: |
        image:
          tag: v3.1.0

        env:
          DB_HOSTNAME: 'immich-postgresql'
          DB_DATABASE_NAME: 'immich'
          DB_USERNAME: 'immich'
          DB_PASSWORD: 'ImmichSuperSecretDBPassword123'
          REDIS_HOSTNAME: 'immich-redis-master'

        immich:
          persistence:
            library:
              existingClaim: immich-library-pvc

        postgresql:
          enabled: true
          image:
            registry: ghcr.io
            repository: immich-app/postgres
            tag: 18-vectorchord1.1.1
          auth:
            username: immich
            password: "ImmichSuperSecretDBPassword123"
            postgresPassword: "ImmichSuperSecretDBPassword123"
            database: immich
          primary:
            extraEnvVars:
              - name: IGNORE_DATABASE_FSTYPE
                value: "true"
            livenessProbe:
              enabled: false
            readinessProbe:
              enabled: false
            resources:
              limits:
                cpu: "1"
                memory: "2Gi"
              requests:
                cpu: "500m"
                memory: "1Gi"
            persistence:
              enabled: true
              size: 20Gi
              storageClass: local-path

        redis:
          enabled: true
          architecture: standalone
          auth:
            enabled: false
          image:
            repository: bitnamilegacy/redis
            tag: 7.2.5-debian-12-r0

        machine-learning:
          enabled: true
          persistence:
            cache:
              enabled: true
              size: 10Gi
              storageClass: local-path

        server:
          probes:
            startup:
              spec:
                initialDelaySeconds: 15
                periodSeconds: 10
                failureThreshold: 120
                timeoutSeconds: 5
          ingress:
            main:
              enabled: true
              ingressClassName: traefik-ingress
              annotations:
                cert-manager.io/cluster-issuer: selfsigned-issuer
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                traefik.ingress.kubernetes.io/router.tls: "true"
              hosts:
                - host: photos.homelab.com
                  paths:
                    - path: /
                      pathType: Prefix
              tls:
                - hosts:
                    - photos.homelab.com
                  secretName: immich-tls-cert
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
