apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://immich-app.github.io/immich-charts'
    chart: immich
    targetRevision: "0.8.4"
    helm:
      values: |
        env:
          DB_HOSTNAME: '{{ .Release.Name }}-postgresql'
          DB_DATABASE_NAME: 'immich'
          DB_USERNAME: 'immich'
          DB_PASSWORD: 'immich'
          REDIS_HOSTNAME: '{{ .Release.Name }}-redis-master'

        immich:
          persistence:
            library:
              existingClaim: immich-library-pvc

        postgresql:
          enabled: true
          image:
            repository: tensorchord/pgvecto-rs
            tag: pg16-v0.2.1
          auth:
            postgresPassword: "ImmichSuperSecretDBPassword123"
            database: immich
          primary:
            persistence:
              enabled: true
              size: 20Gi
              storageClass: local-path

        redis:
          enabled: true
          architecture: standalone
          auth:
            enabled: false
          image:
            repository: bitnamilegacy/redis
            tag: 7.2.5-debian-12-r0

        machine-learning:
          enabled: true
          persistence:
            cache:
              enabled: true
              size: 10Gi
              storageClass: local-path

        server:
          ingress:
            main:
              enabled: true
              ingressClassName: traefik-ingress
              annotations:
                cert-manager.io/cluster-issuer: selfsigned-issuer
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
              hosts:
                - host: photos.homelab.com
                  paths:
                    - path: /
                      pathType: Prefix
              tls:
                - hosts:
                    - photos.homelab.com
                  secretName: immich-tls-cert
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
