apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-ingress
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: default
  source:
    repoURL: 'https://helm.traefik.io/traefik'
    chart: traefik
    targetRevision: "41.1.1"
    helm:
      values: |
        providers:
          kubernetesIngress:
            publishedService:
              enabled: true
              pathOverride: "kube-system/traefik-ingress"
        ports:
          web:
            port: 8000
            expose:
              default: true
            exposedPort: 80
            http:
              redirections:
                entryPoint:
                  to: websecure
                  scheme: https
                  permanent: true
          websecure:
            port: 8443
            expose:
              default: true
            exposedPort: 443
        ingressClass:
          enabled: true
          isDefaultClass: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
