apiVersion: v1
kind: Secret
metadata:
  name: samba-secret
  namespace: samba
type: Opaque
stringData:
  # The password for the Samba share. You can change this to your preferred password.
  SAMBA_PASSWORD: "HomelabStoragePassword123"
