apiVersion: v1
kind: ConfigMap
metadata:
  name: samba-config
  namespace: samba
data:
  config.yml: |
    auth:
      - user: homelab
        group: users
        uid: 1000
        gid: 1000
        password: "HomelabStoragePassword123"

    global:
      - "server min protocol = SMB2"
      - "server max protocol = SMB3"
      - "ntlm auth = yes"
      - "server signing = auto"
      - "smb encrypt = off"
      - "vfs objects = acl_xattr"
      - "map to guest = Bad User"

    share:
      - name: storage
        path: /samba/storage
        browsable: yes
        readonly: no
        guestok: no
        validusers: homelab
        writelist: homelab
        forceuser: homelab
        forcegroup: users
