apiVersion: v1
kind: Service
metadata:
  name: samba
  namespace: samba
  labels:
    app: samba
spec:
  type: LoadBalancer
  ports:
    - name: smb
      port: 445
      targetPort: 445
      protocol: TCP
  selector:
    app: samba
