apiVersion: v1
kind: Secret
metadata:
  name: ghcr-public-immich-charts
  namespace: argocd 
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  url: ghcr.io/immich-app/immich-charts
  enableOCI: "true" 